name: release

on:
  push:
    branches:
      - main
    paths:
      - "**/RELEASE"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pipe-cd/actions-gh-release@v2.6.0
        with:
          release_file: "**/RELEASE"
          token: ${{ secrets.GITHUB_TOKEN }}
